package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/martinmose/agentlink/internal/registry"
	"github.com/spf13/cobra"
)

var (
	detectGenerate bool
)

var detectCmd = &cobra.Command{
	Use:   "detect",
	Short: "Auto-detect installed AI coding tools",
	Long: `Scan the system for installed AI coding tools and report what was found.

Checks known configuration directories and PATH for each tool in the registry.
Use --generate to produce a .agentlink.yaml pre-filled with detected tool paths.`,
	RunE: runDetect,
}

func init() {
	detectCmd.Flags().BoolVar(&detectGenerate, "generate", false, "generate .agentlink.yaml from detected tools")
	rootCmd.AddCommand(detectCmd)
}

func runDetect(cmd *cobra.Command, args []string) error {
	allTools := registry.All()
	detected := registry.DetectAll()

	fmt.Printf("Tool Detection\n")
	fmt.Printf("==============\n\n")

	// Report all known tools with status
	fmt.Printf("Installed tools:\n\n")
	installedCount := 0
	for _, d := range detected {
		installedCount++
		fmt.Printf("  %-20s  detected via %s (%s)\n", d.Tool.Name, d.Method, d.Details)
		if verbose {
			if d.Tool.GlobalConfigPath != "" {
				fmt.Printf("  %-20s  global config: %s\n", "", d.Tool.GlobalConfigPath)
			}
			if d.Tool.RepoFileName != "" {
				fmt.Printf("  %-20s  repo file: %s\n", "", d.Tool.RepoFileName)
			}
			if d.Tool.ReadsAgentsMD {
				fmt.Printf("  %-20s  reads AGENTS.md natively\n", "")
			}
		}
	}

	if installedCount == 0 {
		fmt.Printf("  (none detected)\n")
	}

	fmt.Printf("\n%d of %d known tools detected\n", installedCount, len(allTools))

	// Show tools with global config paths
	globalTools := filterDetectedWithGlobalConfig(detected)
	if len(globalTools) > 0 {
		fmt.Printf("\nTools with global config paths:\n\n")
		homeDir, _ := os.UserHomeDir()
		for _, d := range globalTools {
			expanded := expandDetectHome(d.Tool.GlobalConfigPath, homeDir)
			exists := "missing"
			if _, err := os.Stat(expanded); err == nil {
				exists = "exists"
			}
			fmt.Printf("  %-20s  %s (%s)\n", d.Tool.Name, d.Tool.GlobalConfigPath, exists)
		}
	}

	// Generate config if requested
	if detectGenerate {
		return generateConfig(detected)
	}

	return nil
}

func generateConfig(detected []registry.Detected) error {
	configPath := ".agentlink.yaml"

	if _, err := os.Stat(configPath); err == nil {
		if !force {
			printError(".agentlink.yaml already exists (use --force to overwrite)")
			return fmt.Errorf("config file already exists")
		}
	}

	// Build link list from detected tools
	var links []string
	seen := make(map[string]bool)

	// Always include AGENTS.md as a link target
	seen["AGENTS.md"] = true

	for _, d := range detected {
		if d.Tool.RepoFileName != "" && d.Tool.RepoFileName != "AGENTS.md" {
			if !seen[d.Tool.RepoFileName] {
				links = append(links, d.Tool.RepoFileName)
				seen[d.Tool.RepoFileName] = true
			}
		}
	}

	if dryRun {
		printInfo("Would generate .agentlink.yaml with %d links", len(links)+1)
		return nil
	}

	// Write the config
	var b strings.Builder
	b.WriteString("# Generated by agentlink detect\n")
	b.WriteString("# Source file is your single source of truth.\n")
	b.WriteString("# All links below are symlinks pointing to it.\n\n")
	b.WriteString("source: AGENTS.md\n")
	b.WriteString("links:\n")

	for _, link := range links {
		b.WriteString(fmt.Sprintf("  - %s\n", link))
	}

	if err := os.WriteFile(configPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	abs, _ := filepath.Abs(configPath)
	printOK("Generated %s with %d links from detected tools", abs, len(links))
	return nil
}

func filterDetectedWithGlobalConfig(detected []registry.Detected) []registry.Detected {
	var result []registry.Detected
	for _, d := range detected {
		if d.Tool.GlobalConfigPath != "" {
			result = append(result, d)
		}
	}
	return result
}

func expandDetectHome(path, homeDir string) string {
	if len(path) >= 2 && path[:2] == "~/" {
		return filepath.Join(homeDir, path[2:])
	}
	return path
}
